#ifndef MPI_CONSTANTS_H
#define MPI_CONSTANTS_H

#define FILTER_EDGE
// #define FILTER_ZERO_DEGREE
// #define PUT_RECOVER_ZERO_DEGREE_IN_VALIDATION

// #define SHOWDEBUG
#define SHOWTIMER

#define DOPRINT

#define NEW_GRAPH_BUILDER

#define SINGLE_PROC_VALIDATION

#define ROOT_SKIP_ZERO_DEGREE

// #define USE_OPENMP

#endif //MPI_CONSTANTS_H
